FROM node:20-alpine

WORKDIR /app/client-web

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

ARG NEXT_PUBLIC_API_ENDPOINT
ENV NEXT_PUBLIC_API_ENDPOINT $NEXT_PUBLIC_API_ENDPOINT

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
