FROM node:latest

WORKDIR /app/client-web

COPY package*.json ./
RUN npm install

COPY . .

ARG NEXT_PUBLIC_API_ENDPOINT
ENV NEXT_PUBLIC_API_ENDPOINT $NEXT_PUBLIC_API_ENDPOINT

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
